version: '3'
services:
    php-teste-smart:
        container_name: php-teste-smart
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./:/var/www/html/
        ports:
            - 8009:80
    
    db:
        container_name: db
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3309:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8089:80"
        volumes:
            - ./uploads.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini