version: "2"

services:
  database:
    container_name: database
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=project"
    ports:
      - "3307:3306"
      
  app:
    container_name: app
    build: ./docker_config
    depends_on:
      - database
    volumes:
      - ./:/var/www/html/
    ports:
      - 8080:80
    links:
      - database
